# Generated by Django 6.0.5 on 2026-05-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=80)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=60)),
                ('unit', models.CharField(choices=[('L', 'Litres'), ('kg', 'Kilograms'), ('kWh', 'Kilowatt-hours'), ('km', 'Kilometres'), ('pkm', 'Passenger-kilometres'), ('night', 'Hotel nights'), ('t', 'Metric tonnes')], max_length=10)),
                ('co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source_name', models.CharField(max_length=120)),
                ('source_year', models.PositiveSmallIntegerField()),
                ('version', models.CharField(max_length=40)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-source_year', 'category_code'],
                'unique_together': {('category_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=10)),
                ('source_row_json', models.JSONField(help_text='Verbatim source row, never modified after ingest')),
                ('raw_id', models.CharField(blank=True, max_length=200)),
                ('raw_date_str', models.CharField(blank=True, max_length=50)),
                ('raw_unit', models.CharField(blank=True, max_length=20)),
                ('raw_quantity_str', models.CharField(blank=True, max_length=50)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('category_code', models.CharField(max_length=60)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased electricity'), (3, 'Scope 3 — Value chain')])),
                ('facility_or_cc', models.CharField(blank=True, help_text='Plant name, facility, or cost center', max_length=200)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, help_text='Quantity in canonical unit (L, kWh, km, nights)', max_digits=18)),
                ('unit_canonical', models.CharField(choices=[('L', 'Litres'), ('kg', 'Kilograms'), ('kWh', 'Kilowatt-hours'), ('km', 'Kilometres'), ('pkm', 'Passenger-km'), ('night', 'Hotel nights')], max_length=10)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='kg CO2e, computed from quantity × emission factor', max_digits=18)),
                ('origin_iata', models.CharField(blank=True, max_length=4)),
                ('destination_iata', models.CharField(blank=True, max_length=4)),
                ('cabin_class', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after batch audit sign-off; no further edits allowed')),
                ('review_note', models.TextField(blank=True)),
                ('is_flagged_auto', models.BooleanField(default=False, help_text='Auto-flagged by parser for analyst attention')),
                ('flag_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.emissionfactor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='core.emissionrecord')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=12)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PlantCodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('grid_region', models.CharField(blank=True, help_text='Grid region code for electricity emission factor lookup', max_length=80)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
